[env:nano]
platform = atmelavr
board = nanoatmega328
framework = arduino

upload_port = /dev/cu.usbserial-120
monitor_port = /dev/cu.usbserial-120

upload_speed = 115200
board_build.mcu = atmega328p
board_build.f_cpu = 16000000L

monitor_speed = 115200

lib_deps =
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    nrf24/RF24